### ISSUE TITLE
ProjectView - Создать компонент модальное окно

### ISSUE THREAD

**Issue by 375291601334** [kovalenkoiryna15/rsclone#5]
Это должен быть общий компонент модального окна без содержимого - только пустое окно с кнопкой закрытия (обычно модальное окно также закрывается по клику по области вне модального окна). Самый распространенный подход для модальных окон в React - это Порталы (https://ru.reactjs.org/docs/portals.html). Содержимое окна будет отображаться внутри как this.props.children.

**Comment by aneekee** [comment]
Могу предложить использовать библиотечный компонент для этого.
Например в [MaterialUI есть компонент Modal](https://material-ui.com/ru/components/modal/).
