### ISSUE TITLE
TaskListNav - Реализовать компонент Sidebar

### ISSUE THREAD

**Issue by 375291601334** [kovalenkoiryna15/rsclone#8]
Общий компонент без содержимого - можно скрыть/показать по клику на стрелке сбоку. Все содержимое в него помещается через входной параметр children.

**Comment by aneekee** [comment]
Могу предложить использовать библиотечный компонент для этого.
Например в [MaterialUI есть компонент Drawer](https://material-ui.com/ru/components/drawers/).
